version: '3'
services:
  mango1:
    image: server
    environment:
      - APP=mango1
    ports:
      - "8081:5000"
  mango2:
    image: server
    environment:
      - APP=mango2
    ports:
      - "8082:5000"
  apple1:
    image: server
    environment:
      - APP=apple1
    ports:
      - "9081:5000"
  apple2:
    image: server
    environment:
      - APP=apple2
    ports:
      - "9082:5000"